#!/usr/bin/env python3
"""Centralised configuration loaded from environment / .env file."""

from __future__ import annotations

import json, os, sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path("config_dev.env") if os.getenv("DEV") else Path("config.env"))

# ───── Logging ───────────────────────────────────────────────────────────
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

# ───── Telegram ──────────────────────────────────────────────────────────
API_ID       = int(os.getenv("TELEGRAM_API_ID", "0"))
API_HASH     = os.getenv("TELEGRAM_API_HASH", "")
PHONE        = os.getenv("PHONE_NUMBER", "")

# StringSession: base64 session string (generated by gen_session.py)
# If set, file-based sessions are not needed.
SESSION_STRING = os.getenv("TG_SESSION_STRING", "")

# Fallback: file-based session (only used if SESSION_STRING is empty)
SESSION_NAME = os.getenv("SESSION_NAME", "arab-ai")
if not SESSION_NAME.endswith(".session"):
    SESSION_NAME += ".session"
SESSION_PATH = Path(SESSION_NAME).expanduser().resolve()

ARABS_SUMMARY_OUT = int(os.getenv("ARABS_SUMMARY_OUT", "0"))
SMART_CHAT        = int(os.getenv("SMART_CHAT", "0"))

# Reader accounts — each entry can have a "session_string" key for StringSession
TG_READERS_JSON = json.loads(os.getenv("TG_READERS_JSON", "[]"))

# ───── Channel sources ───────────────────────────────────────────────────
ARAB_SOURCES_FILE  = Path(os.getenv("ARAB_SOURCES_FILE", "arab_channels.txt"))
SMART_SOURCES_FILE = Path(os.getenv("SMART_SOURCES_FILE", "smart_channels.txt"))

# ───── Batching ──────────────────────────────────────────────────────────
BATCH_SIZE           = int(os.getenv("BATCH_SIZE", "24"))
MAX_BATCH_AGE        = int(os.getenv("MAX_BATCH_AGE", "300"))
MEDIA_THRESHOLD      = int(os.getenv("MEDIA_THRESHOLD", "3"))
SUMMARY_MIN_INTERVAL = int(os.getenv("SUMMARY_MIN_INTERVAL", "300"))

# ───── Gemini AI ─────────────────────────────────────────────────────────
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL   = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")
GEMINI_URL     = (
    f"https://generativelanguage.googleapis.com/v1beta/models/"
    f"{GEMINI_MODEL}:generateContent"
)
LLM_BUDGET_HOURLY = int(os.getenv("LLM_BUDGET_HOURLY", "120"))
LLM_RPM_LIMIT     = int(os.getenv("LLM_RPM_LIMIT", "14"))

# ───── Correlation ───────────────────────────────────────────────────────
SIGNATURE_MATCH_THRESHOLD = float(os.getenv("SIGNATURE_MATCH_THRESHOLD", "0.5"))
EVENT_MERGE_WINDOW        = int(os.getenv("EVENT_MERGE_WINDOW", "600"))
FLUSH_EVERY               = int(os.getenv("FLUSH_EVERY", "120"))
MIN_SOURCES               = int(os.getenv("MIN_SOURCES", "2"))

# ───── Authority ─────────────────────────────────────────────────────────
AUTHORITY_HIGH_THRESHOLD  = float(os.getenv("AUTHORITY_HIGH_THRESHOLD", "75"))
AUTHORITY_SMART_DEFAULT   = float(os.getenv("AUTHORITY_SMART_DEFAULT", "70"))
AUTHORITY_ARAB_DEFAULT    = float(os.getenv("AUTHORITY_ARAB_DEFAULT", "50"))

# ───── Database ──────────────────────────────────────────────────────────
DB_PATH = Path(os.getenv("DB_PATH", "data/intel.db"))

# ───── Validation ────────────────────────────────────────────────────────
def validate():
    missing = []
    if not API_HASH:          missing.append("TELEGRAM_API_HASH")
    if not PHONE:             missing.append("PHONE_NUMBER")
    if not ARABS_SUMMARY_OUT: missing.append("ARABS_SUMMARY_OUT")
    if not GEMINI_API_KEY:    missing.append("GEMINI_API_KEY")
    if missing:
        print(f"Missing required env vars: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)
